# Generated by Django 3.1.4 on 2020-12-15 22:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(null=True)),
                ('sets', models.IntegerField(null=True)),
                ('reps', models.IntegerField(null=True)),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SplitModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('exercises', models.ManyToManyField(to='workout.ExerciseModel')),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('splits', models.ManyToManyField(to='workout.SplitModel')),
            ],
        ),
        migrations.CreateModel(
            name='LoadModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField()),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='workout.exercisemodel')),
                ('split', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='workout.splitmodel')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='workout.workoutmodel')),
            ],
        ),
    ]
