# Generated by Django 2.2.4 on 2019-09-01 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('reps', models.CharField(choices=[('1x5', '1x5'), ('3x8', '3x8'), ('5x5', '5x5')], max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='SplitModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('exercises', models.ManyToManyField(to='workout.ExerciseModel')),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('splits', models.ManyToManyField(to='workout.SplitModel')),
            ],
        ),
    ]
