# Generated by Django 3.1.4 on 2020-12-16 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercisemodel',
            name='user',
        ),
        migrations.AddField(
            model_name='exercisemodel',
            name='initial_load',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='exercisemodel',
            name='progression',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.DeleteModel(
            name='LoadModel',
        ),
    ]
