# Generated by Django 2.2.4 on 2019-09-05 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercisemodel',
            name='reps',
            field=models.CharField(choices=[('1x5', '1x5'), ('5x5', '5x5'), ('3x8', '3x8')], max_length=4),
        ),
    ]
