# Generated by Django 2.2.4 on 2019-09-11 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0002_auto_20190911_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercisemodel',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
