# Generated by Django 2.2.4 on 2019-11-03 21:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workout', '0003_auto_20190911_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercisemodel',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='exercisemodel',
            name='reps',
            field=models.CharField(choices=[('3x8', '3x8'), ('5x5', '5x5'), ('1x5', '1x5')], max_length=4),
        ),
        migrations.CreateModel(
            name='LoadModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField()),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='workout.ExerciseModel')),
                ('split', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='workout.SplitModel')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='workout.WorkoutModel')),
            ],
        ),
    ]
