# Generated by Django 2.2.4 on 2019-11-07 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0004_auto_20191103_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercisemodel',
            name='reps',
            field=models.CharField(choices=[('5x5', '5x5'), ('1x5', '1x5'), ('3x8', '3x8')], max_length=4),
        ),
    ]
