# Generated by Django 2.2.4 on 2019-11-10 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0005_auto_20191107_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercisemodel',
            name='reps',
            field=models.CharField(max_length=5),
        ),
    ]
