# Generated by Django 2.2.4 on 2019-11-29 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0006_auto_20191110_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercisemodel',
            name='sets',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='exercisemodel',
            name='reps',
            field=models.IntegerField(null=True),
        ),
    ]
