# Generated by Django 3.0.2 on 2020-01-23 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0008_auto_20200123_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercisemodel',
            name='initial_load',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='exercisemodel',
            name='progression',
            field=models.FloatField(null=True),
        ),
        migrations.DeleteModel(
            name='LoadModel',
        ),
    ]
