# Generated by Django 3.0.2 on 2020-01-23 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0009_auto_20200123_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercisemodel',
            name='progression',
            field=models.FloatField(default=0, null=True),
        ),
    ]
